---
apiVersion: v1
kind: Service
metadata:
  name: webtop-kub-app
spec:
  type: NodePort
  selector:
    app: webtop-kub-app
  ports:
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 3000
      targetPort: 3000
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
     # nodePort: 30007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtop-kub-app
  labels:
    app: webtop-kub-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webtop-kub-app
  template:
    metadata:
      labels:
        app: webtop-kub-app
    spec:
      containers:
        - name: webtop-kub-app
          image: ghcr.io/linuxserver/webtop:alpine-gnome
          env:
       #     - name: PASSWORD
        #      value: poopie
          ports:
            - containerPort: 3000
